time_entries_extractor:
    build: time_entries_extractor
    volumes:
      - logstashConfig:/etc/logstash/conf.d
      - timeEntriesExtractorData:/tmp/redmine #must match OUPUTDIR env
      - /backups:/backups

    environment:
      OUTPUTDIR: /tmp/redmine 
      TIMEFROM: 0
      TIMETO: -3
      APIKEY: "changeme"
      REDMINEURL: "changeme"
      CRON_ENTRY: "*/15 * * * *"
      DBUSERNAME: "changeme"
      DBPASSWORD: "changeme"
      DBDATABASE: "changeme"
      DBPORT: "changeme"
      DBHOST: "changeme"
      DBSCHEMA: "changeme"
      FORCEDELETE: 1 #or 0
